# Generated by Django 3.0.5 on 2020-05-11 17:25

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=512)),
                ('details_json', models.TextField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Skillet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillet_id', models.CharField(max_length=200, unique=True)),
                ('skillet_json', models.TextField(default='', max_length=2048)),
                ('repository',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panhandler.RepositoryDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('categories', models.CharField(default='[]', max_length=64)),
                ('skillets', models.ManyToManyField(to='panhandler.Skillet')),
            ],
        ),
    ]
