# Generated by Django 3.0.5 on 2020-05-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panhandler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillet',
            old_name='skillet_id',
            new_name='name',
        ),
    ]
