# Generated by Django 3.0.5 on 2020-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panhandler', '0002_auto_20200511_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorydetails',
            name='deploy_key_path',
            field=models.CharField(default='', max_length=128, null=''),
        ),
    ]
