# Generated by Django 3.0.5 on 2020-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panhandler', '0003_repositorydetails_deploy_key_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorydetails',
            name='deploy_key_priv',
            field=models.CharField(default='', max_length=2048, null=''),
        ),
        migrations.AddField(
            model_name='repositorydetails',
            name='deploy_key_pub',
            field=models.CharField(default='', max_length=2048, null=''),
        ),
    ]
