# Generated by Django 3.0.5 on 2020-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panhandler', '0004_auto_20200522_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillet_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skillet',
            name='repository',
        ),
        migrations.DeleteModel(
            name='RepositoryDetails',
        ),
        migrations.DeleteModel(
            name='Skillet',
        ),
        migrations.AlterField(
            model_name='collection',
            name='skillets',
            field=models.ManyToManyField(to='panhandler.Favorite'),
        ),
    ]
